version: '3'
services:
  app:
    container_name: ip-address-management-api
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: ip-address-management-api/Dockerfile
    ports:
      - '8080:8080'