server:
  port: 8080
  forward-headers-strategy: NATIVE

spring:
  security:
    basic: 
      enable: false
  application:
    name: ip-address-management-api
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://app_database:3306/ip_address_management_db?useTimezone=true&serverTimezone=UTC
    username: root
    password: senhasecreta
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
    
# validate: validate the schema, makes no changes to the database.
# update: update the schema.
# create: creates the schema, destroying previous data.
# create-drop: drop the schema at the end of the session
# none: is all other cases.
